language: java

jdk:
  - oraclejdk11
  -
script:
  - ./mvnw clean install
  - "mvn cobertura:cobertura"
  - bash <(curl -s https://codecov.io/bash) -t 777a3455-e6cd-4486-8397-d605803e0727

after_success:
after_failure: